import { useEffect, useState } from 'react';
import { catalog, champions, decks, items, traits, type ChampionDefinition, type DeckId } from '../content/prototype';
import { applyAction, armyTrait, createGame, frontTrait, isLegal, legalActions, moveCost, RULES, stats, strength } from '../game/rules';
import { chooseAction } from '../game/ai';
import { FRONTS, type Action, type Front, type GameState, type Unit } from '../game/types';
import { restoreGame, SAVE_KEY, serializeGame } from '../persistence/journal';
import { Crown } from './Crown';

const frontInfo = {
  wild: { title: 'The Wild', icon: '❦', benefit: '1 influence · survivors grow & mend', description: 'Winning survivors gain +1 Might (max +2 growth) and mend 1 Guard.' },
  throne: { title: 'The Throne', icon: '♜', benefit: '2 influence · the heart of the contest', description: 'Worth 2 Crown influence. An active Arcanist trait with a surviving Arcanist adds 1.' },
  forge: { title: 'The Forge', icon: '⚒', benefit: '1 influence · gain a component', description: 'Gain 1 component. Spend 2 components and 1 Command to forge an item.' },
};
function seed() { return crypto.getRandomValues(new Uint32Array(1))[0] || 1; }
function load() { try { return restoreGame(localStorage.getItem(SAVE_KEY) ?? ''); } catch { return null; } }

function Card({ card, selected = false, disabled = false, onClick, compact = false, unit, state }: { card: ChampionDefinition; selected?: boolean; disabled?: boolean; onClick?: () => void; compact?: boolean; unit?: Unit; state?: GameState }) {
  const s = unit && state ? stats(state, unit) : { might: card.might, guard: card.guard + (card.ability === 'bulwark' ? 1 : 0), maxGuard: card.guard + (card.ability === 'bulwark' ? 1 : 0) };
  const content = <>
    <div className="card-top"><span className="card-cost" title="Command cost">{card.cost}</span><span className="card-tier">TIER {card.tier}</span><span className="card-stars">{'★'.repeat(unit?.stars ?? 1)}</span></div>
    <div className={`card-art ${card.origin.toLowerCase()}`}><div className="sigil-ring" /><span>{card.glyph}</span>{unit?.item && <span className="equipped" title={items.find(i => i.id === unit.item)?.name}>{unit.item === 'shp-item-blade' ? '⚔' : '⬟'}</span>}</div>
    <div className="card-body"><strong>{card.name}</strong><div className="card-traits">{card.origin} <span>·</span> {card.class}</div>{!compact && <p>{card.text}</p>}</div>
    <div className="card-stats"><span title="Might">⚔ <b>{s.might}</b></span>{unit && unit.growth > 0 && <small title="Wild growth">+{unit.growth} ❦</small>}<span className={unit?.wounds ? 'wounded' : ''} title={`Guard: ${s.guard} of ${s.maxGuard}`}>⬟ <b>{s.guard}</b>{unit && unit.wounds > 0 && <small>/{s.maxGuard}</small>}</span></div>
  </>;
  const cls = `champion-card ${compact ? 'compact' : ''} ${selected ? 'selected' : ''} ${unit && unit.stars > 1 ? 'ascended' : ''}`;
  return onClick ? <button className={cls} disabled={disabled} onClick={onClick} aria-pressed={selected} aria-label={`${card.name}, ${s.might} Might, ${s.guard} Guard, ${card.cost} Command${unit ? `, ${unit.stars} stars` : ''}`}>{content}</button> : <div className={cls}>{content}</div>;
}

function Rules({ close }: { close: () => void }) {
  return <div className="modal-backdrop"><section className="rules-modal" role="dialog" aria-modal="true" aria-labelledby="rules-title"><button className="close-button" onClick={close} aria-label="Close rules">×</button><span className="eyebrow">A crown. Two sovereigns. Three fronts.</span><h2 id="rules-title">How to ascend</h2><p className="rules-lead">Control the battlefronts. Pull the Crown toward you. Hold your claim.</p>
    <div className="rules-grid"><article><b>01 / Alternate actions</b><p>Deploy a champion, move one, ascend, forge an item, or pass. One action, then your rival acts. Two consecutive passes start battle.</p></article><article><b>02 / Spend Command</b><p>Start with 4 Command. It increases by 1 each round, up to 8, and refreshes each round. Unspent Command is lost. Draw 2 cards each new round.</p></article><article><b>03 / Fight for the fronts</b><p>Both armies strike simultaneously. Add Might and deal it to the enemy’s first card, spilling to the next. Guard absorbs damage; at 0, a champion falls. Damage persists.</p></article><article><b>04 / Move the Crown</b><p>Compare surviving Might, using values from before combat. Higher wins; ties award nothing. The Wild and Forge give 1 influence; the Throne gives 2. Subtract rival influence, then move the Crown.</p></article><article><b>05 / Ascend your champions</b><p>Select a matching card in hand and ascend a deployed champion for 1 Command. Each consumed copy adds a star, +2 Might, +3 Guard and fully mends it. Maximum ★★★.</p></article><article><b>06 / Seal your claim</b><p>Reach your end of the Crown track, then win net influence in a later battle while still at that end. A tie delays victory; a reversal breaks the claim. Round 18 ends by Crown position; centre is a draw.</p></article></div>
    <h3>Choose what to concede</h3><div className="rules-fronts">{FRONTS.map(f => <article key={f}><span>{frontInfo[f].icon}</span><b>{frontInfo[f].title}</b><p>{frontInfo[f].description}</p></article>)}</div>
    <h3>Six prototype traits</h3><div className="trait-rules">{traits.map(t => <p key={t.name}><b>{t.name}</b> — {t.scope}: {t.text}</p>)}</div><p className="fine-print">Duplicates do not count as distinct champions. Trait effects are locked at the start of battle. At most 3 champions per player per front. Deployment and movement join the back of that front’s row. One item per champion. Maximum hand: 10; excess draws are discarded. No reshuffles.</p><p className="prototype-notice">All champion names, traits, items, symbols and balance values here are noncanonical playtest placeholders. Collector treatments never change gameplay.</p><button className="primary-button" onClick={close}>I’m ready to command <span>→</span></button>
  </section></div>;
}

export function App() {
  const [game, setGame] = useState<GameState | null>(null);
  const [saved, setSaved] = useState<GameState | null>(() => load());
  const [deckId, setDeckId] = useState<DeckId>('dawn');
  const [handIndex, setHandIndex] = useState<number | null>(null);
  const [selectedUnit, setSelectedUnit] = useState<number | null>(null);
  const [rules, setRules] = useState(false), [showLog, setShowLog] = useState(false);
  const [showRoster, setShowRoster] = useState(false), [error, setError] = useState('');
  const [resolutionStep, setResolutionStep] = useState(0);
  const [sound, setSound] = useState(false);
  const [leaving, setLeaving] = useState(false);
  const [inspected, setInspected] = useState<Unit | null>(null);
  const start = (id = deckId, sameSeed?: number) => { setGame(createGame(sameSeed ?? seed(), id, id === 'dawn' ? 'wild' : 'dawn')); setHandIndex(null); setSelectedUnit(null); setError(''); setShowLog(false); };
  const send = (action: Action) => {
    if (!game) return;
    try { setGame(applyAction(game, action)); setHandIndex(null); setSelectedUnit(null); setError(''); }
    catch { setError('That action is unavailable. Select another card or front.'); }
  };
  useEffect(() => { if (game) { try { localStorage.setItem(SAVE_KEY, serializeGame(game)); setSaved(game); } catch { /* Play remains available without storage. */ } } }, [game]);
  useEffect(() => {
    if (!game || game.phase !== 'planning' || game.active !== 1) return;
    const timer = setTimeout(() => {
      try { const action = chooseAction(game); setGame(applyAction(game, action)); }
      catch { setError('Rival action failed. Reload to restore the last valid journal.'); }
    }, 650);
    return () => clearTimeout(timer);
  }, [game]);
  useEffect(() => {
    if (!game || !game.lastResolution || game.phase === 'planning') { setResolutionStep(0); return; }
    setResolutionStep(0);
    const timers = [1800, 3600, 5400, 8000].map((ms, i) => setTimeout(() => setResolutionStep(i + 1), ms));
    return () => timers.forEach(clearTimeout);
  }, [game?.lastResolution?.round, game?.phase]);
  useEffect(() => {
    if (!sound || resolutionStep !== 3) return;
    const context = new AudioContext();
    [196, 293.66, 392].forEach((freq, i) => { const o = context.createOscillator(), gain = context.createGain(); o.type = 'sine'; o.frequency.value = freq; gain.gain.setValueAtTime(0, context.currentTime); gain.gain.linearRampToValueAtTime(.035, context.currentTime + .03 + i * .09); gain.gain.exponentialRampToValueAtTime(.001, context.currentTime + 1.1); o.connect(gain); gain.connect(context.destination); o.start(); o.stop(context.currentTime + 1.2); });
    const timer = setTimeout(() => { void context.close(); }, 1600); return () => { clearTimeout(timer); void context.close(); };
  }, [resolutionStep, sound]);
  useEffect(() => {
    const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') { setRules(false); setShowRoster(false); setShowLog(false); setLeaving(false); setInspected(null); setHandIndex(null); setSelectedUnit(null); } };
    window.addEventListener('keydown', escape); return () => window.removeEventListener('keydown', escape);
  }, []);
  function exportReplay() {
    if (!game) return;
    const url = URL.createObjectURL(new Blob([serializeGame(game)], { type: 'application/json' }));
    const a = document.createElement('a'); a.href = url; a.download = `sovereigns-hand-${game.initialSeed}.json`; a.click(); URL.revokeObjectURL(url);
  }
  const header = <header className="site-header"><button className="brand" onClick={() => game ? setLeaving(true) : undefined}><Crown /><span>CROWNFALL<small>SOVEREIGN’S HAND</small></span></button><nav><span className="version-pill"><i /> V0.1 PLAYTEST</span><button onClick={() => setRules(true)}>How to play <span>↗</span></button>{game && <button onClick={() => setSound(!sound)} aria-label={sound ? 'Mute sound' : 'Enable sound'}>{sound ? '♫ Sound on' : '♫ Sound off'}</button>}</nav></header>;
  if (!game) return <div className="app menu">{header}<main className="menu-main"><div className="menu-copy"><span className="eyebrow">NORTHERN SUMMIT STUDIOS PRESENTS</span><h1>One Crown.<br />Two Sovereigns.<br /><em>Your move.</em></h1><p className="hero-description">A tactical contest of command and consequence.<br />Control three battlefronts. Ascend your champions.<br />Pull the Crown toward your throne.</p><div className="menu-actions"><button className="primary-button" onClick={() => start()}>Enter the battle <span>→</span></button><button className="text-button" onClick={() => setRules(true)}>Learn the rules</button></div>{saved && saved.phase !== 'finished' && <button className="resume-button" onClick={() => { setGame(saved); setDeckId(saved.deckIds[0]); }}>Resume battle · Round {saved.round} →</button>}<div className="hero-meta"><span>01 VS 01</span><span>ALTERNATING ACTIONS</span><span>DIGITAL & TABLETOP</span></div></div><div className="crown-scene"><div className="scene-orbit orbit-one" /><div className="scene-orbit orbit-two" /><div className="scene-rune rune-one">❦</div><div className="scene-rune rune-two">⚒</div><div className="scene-rune rune-three">♜</div><div className="crown-pedestal" /><Crown className="hero-crown" /><span className="scene-caption">THE CROWN BELONGS TO NO ONE.<br /><b>YET.</b></span></div></main><section className="deck-selection"><div className="section-label"><span className="eyebrow">CHOOSE YOUR STARTER</span><span>30 cards · 10 champions · 3 copies each</span></div><div className="deck-options">{(Object.keys(decks) as DeckId[]).map(id => <button key={id} className={`deck-option ${deckId === id ? 'chosen' : ''}`} onClick={() => setDeckId(id)} aria-pressed={deckId === id}><span className={`deck-symbol ${id}`}>{id === 'dawn' ? '☀' : '❦'}</span><span><b>{decks[id].name}</b><small>{decks[id].description}</small></span><span className="deck-radio">{deckId === id ? '●' : '○'}</span></button>)}</div><button className="text-button roster-link" onClick={() => setShowRoster(true)}>Inspect the 15-champion prototype roster ↗</button></section><footer className="menu-footer"><span>CROWNFALL / A SECOND PATH TO ASCENSION</span><span>Noncanonical playtest content · No purchases · Local AI</span></footer>{rules && <Rules close={() => setRules(false)} />}{showRoster && <div className="modal-backdrop"><section className="roster-modal" role="dialog" aria-modal="true" aria-label="Prototype roster"><button className="close-button" onClick={() => setShowRoster(false)} aria-label="Close roster">×</button><span className="eyebrow">NONCANONICAL PLAYTEST SET</span><h2>The first fifteen</h2><p>Stable gameplay definitions. Placeholder identities. Equal gameplay across all collector treatments.</p><div className="roster-grid">{champions.map(c => <Card key={c.id} card={c} />)}</div></section></div>}</div>;

  const p = game.players[0], rival = game.players[1], yourTurn = game.phase === 'planning' && game.active === 0;
  const chosenCard = handIndex !== null ? catalog[p.hand[handIndex]] : null;
  const chosenUnit = game.units.find(u => u.uid === selectedUnit && u.owner === 0);
  const actions = legalActions(game);
  const resolving = game.phase !== 'planning' && game.lastResolution !== null;
  const displayedCrown = resolving && resolutionStep < 3 ? game.lastResolution!.from : game.crown;
  const actionAllowed = (action: Action) => yourTurn && isLegal(game, action);
  const hint = chosenCard ? `Deploy ${chosenCard.name} to a front, or ascend a matching champion.` : chosenUnit ? `${catalog[chosenUnit.card].name} selected. Reposition or forge equipment below.` : yourTurn ? 'Choose a card to deploy. Select a champion to reposition or equip.' : game.phase === 'planning' ? 'Your rival is considering the battlefronts…' : 'Both Sovereigns have passed. The battlefronts resolve.';
  return <div className="app match">{header}<main className="match-main"><section className="match-heading"><div><span className="eyebrow">{decks[game.deckIds[0]].name} VS {decks[game.deckIds[1]].name}</span><h1>Command the battlefronts.</h1></div><div className="round-indicator"><span>ROUND</span><b>{String(game.round).padStart(2, '0')}</b><small>/ {RULES.maxRounds}</small></div><button className="text-button" onClick={() => setShowLog(!showLog)}>Battle journal ↗</button></section>
    <section className="crown-track" aria-label={`Crown position: ${game.crown}. Positive is toward you.`}><div className="sovereign-marker you"><span>♜</span><b>YOUR ASCENSION</b>{game.claim === 0 && <small>CLAIM PENDING</small>}</div><div className="track-middle"><div className="track-label"><span>← YOUR CROWN</span><span>{game.claim !== null ? 'HOLD THE END. WIN INFLUENCE AGAIN.' : 'CONTROL THE FRONTS. PULL THE CROWN.'}</span><span>RIVAL’S CROWN →</span></div><div className="track-rail"><div className="track-line" />{Array.from({ length: 13 }, (_, i) => <span className={`track-node ${i === 6 ? 'centre' : ''} ${i === 0 || i === 12 ? 'endpoint' : ''}`} key={i} />)}<div className="track-crown" style={{ left: `${(6 - displayedCrown) / 12 * 100}%` }}><Crown /></div></div><div className="track-caption">{displayedCrown === 0 ? 'The Crown rests at the centre' : `${Math.abs(displayedCrown)} steps toward ${displayedCrown > 0 ? 'your Sovereign' : 'the rival'}`}</div></div><div className="sovereign-marker rival"><span>♜</span><b>RIVAL’S ASCENSION</b>{game.claim === 1 && <small>CLAIM PENDING</small>}</div></section>
    <div className="player-bar rival-bar"><div><span className="avatar">♜</span><b>The Ashen Sovereign <small>LOCAL AI</small></b></div><div className="player-resources"><span>{rival.hand.length} cards</span><span>{rival.deck.length} deck</span><span title="Forge components">⚒ {rival.components}</span><span className="command-display">⌘ {rival.command} <small>COMMAND</small></span></div></div>
    <section className="battlefield" aria-label="Three battlefronts">{FRONTS.map((front, frontIndex) => {
      const info = frontInfo[front], result = game.lastResolution?.fronts[frontIndex];
      const frontClass = resolving && resolutionStep >= frontIndex ? `resolved ${result?.winner === 0 ? 'won' : result?.winner === 1 ? 'lost' : 'tied'}` : '';
      return <article className={`battlefront front-${front} ${frontClass}`} key={front}><div className="front-heading"><span>{info.icon}</span><div><h2>{info.title}</h2><p>{info.benefit}</p></div><span className="influence-badge">{front === 'throne' ? '2' : '1'}<small>INFL.</small></span></div><div className="front-body"><div className="front-landscape"><span>{info.icon}</span></div><div className="unit-row enemy-row">{game.units.filter(u => u.front === front && u.owner === 1).map(u => <Card key={u.uid} card={catalog[u.card]} unit={u} state={game} compact onClick={() => setInspected(u)} />)}{!game.units.some(u => u.front === front && u.owner === 1) && <span className="empty-row">Rival’s territory</span>}</div><div className="front-divider"><span className="rival-power">{strength(game, 1, front)}</span><span className="front-divider-label">{resolving && resolutionStep >= frontIndex ? result?.winner === 0 ? 'YOU CONTROL' : result?.winner === 1 ? 'RIVAL CONTROLS' : 'CONTESTED' : 'SURVIVING MIGHT WINS'}</span><span className="your-power">{strength(game, 0, front)}</span></div><div className="unit-row own-row">{game.units.filter(u => u.front === front && u.owner === 0).map(u => <div className="unit-wrapper" key={u.uid}><Card card={catalog[u.card]} unit={u} state={game} compact selected={selectedUnit === u.uid} onClick={() => { if (!yourTurn) return; setSelectedUnit(selectedUnit === u.uid ? null : u.uid); if (chosenCard?.id !== u.card) setHandIndex(null); }} />{handIndex !== null && chosenCard?.id === u.card && actionAllowed({ type: 'ascend', handIndex, uid: u.uid }) && <button className="ascend-button" onClick={() => send({ type: 'ascend', handIndex, uid: u.uid })}>Ascend {'★'.repeat(u.stars + 1)} · 1⌘</button>}</div>)}{!game.units.some(u => u.front === front && u.owner === 0) && <span className="empty-row">Your territory</span>}</div></div><div className="front-action">{chosenCard && handIndex !== null ? <button disabled={!actionAllowed({ type: 'deploy', handIndex, front })} onClick={() => send({ type: 'deploy', handIndex, front })}>Deploy here <span>{chosenCard.cost}⌘</span></button> : chosenUnit ? <button disabled={!actionAllowed({ type: 'move', uid: chosenUnit.uid, front })} onClick={() => send({ type: 'move', uid: chosenUnit.uid, front })}>{chosenUnit.front === front ? 'Current battlefront' : 'Reposition here'} <span>{chosenUnit.front === front ? '•' : `${moveCost(game, chosenUnit)}⌘`}</span></button> : <span>{info.description}</span>}</div></article>;
    })}</section>
    <div className="player-bar own-bar"><div><span className="avatar">♜</span><b>Your Sovereign <small>{yourTurn ? 'YOUR ACTION' : resolving ? 'BATTLE RESOLUTION' : 'RIVAL’S ACTION'}</small></b></div><div className="player-resources"><span>{p.deck.length} deck</span><span>{p.discard.length} discard</span><span title="Forge components">⚒ {p.components}</span><span className="command-display">⌘ {p.command}<small>COMMAND</small></span></div></div>
    <section className="action-bar" aria-live="polite"><div><span className={`turn-light ${yourTurn ? 'active' : ''}`} /><p>{hint}</p></div><button className="pass-button" disabled={!yourTurn} onClick={() => send({ type: 'pass' })}>{game.passes === 1 && yourTurn ? 'Pass & resolve' : 'Pass action'} <span>→</span></button></section>
    {chosenUnit && <div className="equipment-panel"><p className="selected-ability"><b>{catalog[chosenUnit.card].name}</b> · {catalog[chosenUnit.card].text}</p><span>FORGE / {p.components} COMPONENTS</span>{items.map(item => <button key={item.id} disabled={!actionAllowed({ type: 'equip', uid: chosenUnit.uid, item: item.id })} onClick={() => send({ type: 'equip', uid: chosenUnit.uid, item: item.id })}>{item.id === 'shp-item-blade' ? '⚔' : '⬟'} {item.name} · {item.text}<small>2 components + 1⌘</small></button>)}{chosenUnit.item && <small>Already equipped. One item per champion.</small>}<button className="text-button" onClick={() => { setSelectedUnit(null); setHandIndex(null); }}>Cancel</button></div>}
    <section className="hand-section"><div className="hand-label"><b>YOUR HAND <span>{p.hand.length} / 10</span></b><span>Select a card, then choose a front · matching copies ascend</span><button className="text-button" onClick={() => { setHandIndex(null); setSelectedUnit(null); }}>Clear selection</button></div><div className="hand-cards">{p.hand.map((id, index) => <Card key={`${index}:${id}`} card={catalog[id]} selected={handIndex === index} disabled={!yourTurn} onClick={() => { setHandIndex(handIndex === index ? null : index); setSelectedUnit(null); }} />)}{p.hand.length === 0 && <p className="empty-hand">No cards in hand. Command your surviving champions, forge an item, or pass.</p>}</div></section>
    <div className="active-traits"><span>ARMY TRAITS</span>{['Vanguard', 'Arcanist', 'Strider'].map(t => <span key={t} className={armyTrait(game, 0, t) ? 'trait-active' : ''}>{t} {armyTrait(game, 0, t) ? '✓' : '○'}</span>)}<span>FRONT TRAITS</span>{FRONTS.map(f => <span key={f}>{frontInfo[f].title}: {['Dawnkin', 'Ironbound', 'Wildborn'].filter(t => game.units.some(u => u.owner === 0 && u.front === f && frontTrait(game, u, t))).join(', ') || '—'}</span>)}</div><footer className="match-footer"><span>Noncanonical prototype · Seed {game.initialSeed}</span><button className="text-button" onClick={exportReplay}>Export deterministic replay ↗</button></footer>{error && <p className="error-message" role="alert">{error}</p>}
  </main>
  {resolving && <div className="resolution-dock" role="status"><div className="resolution-title"><span className="eyebrow">BATTLE {game.lastResolution!.round}</span><h2>{resolutionStep < 3 ? `${frontInfo[FRONTS[Math.min(resolutionStep, 2)]].title} resolves` : game.phase === 'finished' ? game.winner === 0 ? 'You have ascended.' : game.winner === 1 ? 'The rival has ascended.' : 'The Crown remains unclaimed.' : game.claim !== null ? 'An Ascension claim is made.' : game.crown === game.lastResolution!.from ? 'The Crown holds.' : 'The Crown moves.'}</h2><p>{resolutionStep < 3 ? 'Both armies strike. The survivors decide control.' : `Influence ${game.lastResolution!.influence[0]} — ${game.lastResolution!.influence[1]}. ${game.phase === 'finished' ? game.round >= 18 ? 'Round limit reached; Crown position decides.' : 'A claim was held through a second decisive battle.' : game.claim !== null ? 'Win net influence again at the endpoint to seal victory.' : 'A new round. A new decision.'}`}</p></div><div className="resolution-results">{game.lastResolution!.fronts.map((f, i) => <div key={f.front} className={resolutionStep >= i ? 'revealed' : ''}><b>{frontInfo[f.front].title}</b><span>{resolutionStep >= i ? f.winner === 0 ? `You +${f.influence}` : f.winner === 1 ? `Rival +${f.influence}` : 'Tied' : '…'}</span><small>{f.before[0]} vs {f.before[1]} → {f.after[0]} vs {f.after[1]}</small><small>Incoming: {f.damage[0]} / {f.damage[1]}<br />{f.fallen.length} fallen</small></div>)}</div><div className="resolution-buttons">{resolutionStep < 4 ? <button className="primary-button" onClick={() => setResolutionStep(4)}>Skip animation →</button> : game.phase === 'finished' ? <><button className="primary-button" onClick={() => start(game.deckIds[0])}>Rematch · new draw →</button><button className="text-button" onClick={() => { setGame(null); setDeckId(game.deckIds[0]); }}>Choose another deck</button></> : <button className="primary-button" onClick={() => send({ type: 'continue' })}>Begin round {game.round + 1} →</button>}</div></div>}
  {showLog && <aside className="journal" aria-label="Battle journal"><button className="close-button" onClick={() => setShowLog(false)} aria-label="Close journal">×</button><span className="eyebrow">EVERY ACTION. EVERY CONSEQUENCE.</span><h2>Battle journal</h2><div>{game.log.slice().reverse().map((entry, i) => <p key={i}>{entry}</p>)}</div><button className="text-button" onClick={exportReplay}>Export replay ↗</button></aside>}
  {rules && <Rules close={() => setRules(false)} />}
  {inspected && <div className="modal-backdrop"><section className="inspection-modal" role="dialog" aria-modal="true" aria-label="Champion inspection"><button className="close-button" onClick={() => setInspected(null)} aria-label="Close inspection">×</button><span className="eyebrow">NONCANONICAL PLAYTEST CHAMPION</span><h2>{catalog[inspected.card].name}</h2><Card card={catalog[inspected.card]} unit={inspected} state={game} /><p>{catalog[inspected.card].text}</p><p>{inspected.stars} stars · {inspected.wounds} wounds · {inspected.growth} growth<br />{inspected.item ? items.find(i => i.id === inspected.item)?.name : "No equipment"}</p><small>Gameplay ID: {inspected.card}<br />Collector treatments never change gameplay.</small></section></div>}
  {leaving && <div className="modal-backdrop"><section className="confirm-modal" role="dialog" aria-modal="true" aria-label="Return to menu"><Crown /><h2>Return to your throne?</h2><p>Your match is saved on this browser. You can resume from the menu.</p><button className="primary-button" onClick={() => { setGame(null); setLeaving(false); }}>Return to menu</button><button className="text-button" onClick={() => setLeaving(false)}>Keep playing</button></section></div>}
  </div>;
}
