// Run with npm run proto:cardprompts. Card content is never rewritten.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import { ALL_LINES } from '../../src/v02/content/cards.ts';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const spec = readFileSync(join(root, 'card-template/CARD_TEMPLATE.md'), 'utf8');
const iconSection = spec.split('## Trait icons')[1].split('## Keyword reminder')[0];
const icons = new Map([...iconSection.matchAll(/^\| ([^|]+) \| ([^|]+) \|$/gm)]
  .filter(([, trait]) => trait.trim() !== 'Trait' && !trait.includes('---'))
  .map(([, trait, icon]) => [trait.trim(), icon.trim()]));
const reminderSection = spec.split('## Keyword reminder text (exact wording)')[1].split('## Numbering')[0];
const reminders = new Map([...reminderSection.matchAll(/(\w+) \*\(([^]*?)\)\*/g)]
  .map(([, keyword, reminder]) => [keyword, `(${reminder})`]));
const cap = s => s[0].toUpperCase() + s.slice(1);
const pad = n => String(n).padStart(3, '0');
const stars = n => '★'.repeat(n);
const slug = s => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const presentation = text => text.replace(/\b(Arrival|Ascend|Attack|Block|Defeat):(?: (Scorch \d+|Shield))?/g, '**$&**');
const rulesLines = text => text ? text.split(/(?<=\.)\s+(?=[A-Z+])/).map(presentation) : [];
const tracker = ['# Card art tracker', '', 'Generated by `npm run proto:cardprompts`; statuses are retained by set and card numbers.', '', '| Set | Champion | Card numbers | Sheet file name | Status |', '| --- | --- | --- | --- | --- |'];
// Preserve production progress on subsequent regeneration, without deleting files.
let oldTracker = '';
try { oldTracker = readFileSync(join(root, 'card-prompts/CARD_ART_TRACKER.md'), 'utf8'); }
catch (error) { if (error.code !== 'ENOENT') throw error; }
const oldStatuses = new Map(oldTracker.split('\n').filter(l => /^\| [12] \|/.test(l)).map(l => {
  const c = l.split('|').map(x => x.trim()); return [`${c[1]}:${c[3]}`, c[5]];
}));
let total = 0;
for (const set of [1, 2]) {
  const master = readFileSync(join(root, `MASTER_CARD_LIST_SET${set}.md`), 'utf8');
  const championSection = master.split(/\n## Champions[^\n]*\n/)[1]?.split(/\n## /)[0];
  assert(championSection, `Set ${set}: missing Champions section`);
  const groups = championSection.split('\n### ').slice(1);
  const lines = ALL_LINES.filter(l => (l.set ?? 1) === set && (l.family ?? 'champion') === 'champion');
  assert.equal(groups.length, lines.length);
  const outputDir = join(root, `card-prompts/set${set}`);
  mkdirSync(outputDir, { recursive: true });
  for (const group of groups) {
    const heading = group.split('\n')[0];
    const line = lines.find(l => heading === `${l.name}, ${l.title}${l.epithetProposed ? ' (PROPOSED epithet)' : ''}`);
    assert(line, `Unknown champion: ${heading}`);
    const metadata = group.split('\n')[1].replace(/^\*|\*$/g, '').split(' · ');
    const [tier] = metadata;
    // Collector rarity is independent of champion tier. The locked reference is
    // the C (Core) printing; no per-card collector assignments exist in the data.
    const rarityLetter = 'C';
    // The master-list writer escapes literal pipes inside fields.
    const rows = group.split('\n').filter(l => /^\| S[12]-\d+ \|/.test(l)).map(l =>
      l.slice(1, -1).split(/(?<!\\)\|/).map(c => c.trim().replace(/\\\|/g, '|')));
    assert.equal(rows.length, 3);
    const numbers = rows.map(r => r[0].split('-')[1]);
    const filename = `cards-${numbers[0]}-${numbers[2]}-${slug(line.name)}`;
    const prompt = [
      'Make these 3 cards in the locked master template, side by side, left to right, in one image. Each card has its OWN text and stats exactly as listed. Never copy text or stats from one card to another.',
      '',
      'References: prototype-v0.2/card-template/champion-template.jpg and CARD_TEMPLATE.md; approved sheets in prototype-v0.2/card-art/set1/. Attach those references and the official trait sheet when pasting this prompt.',
      'Use the same proportions, green-vine gold border, bottom-centre shield crest, parchment text box, name/title bar, gold stars top-right, full-width art, and studio mountain logo as the locked reference. No chevrons, plain black frame, or substituted crest.',
      'Green hexagonal gem on ★. Gold hexagonal gem showing an arrow pointing up AND the number on ★★/★★★. No band or empty band on ★: art goes straight to the trait bar. Ascension bands are dark green with gold laurel leaves at both ends.',
      'Keyword chips with italic exact reminders only when listed. Bold ability name with a full stop; each rules sentence on its own line, bold trigger words and effect numbers as marked below. Markdown marks formatting, not printed asterisks. Never add an ability name when none is listed.',
      'This prompt uses the locked reference’s C (Core) printing; collector rarity is separate from champion tier.',
      'Thin divider above centred italic flavour in curly quotes. Bottom-left orange shield with sword icon = Might; bottom-right blue shield with shield icon = Guard.', '',
    ];
    const risks = ['No frame drift: laurels, shield crest, green-vine gold border; no band on ★.', 'Compare every form’s own costs, text, flavour and stats; never copy between forms.'];
    for (let i = 0; i < 3; i++) {
      const f = line.forms[i]; const row = rows[i];
      assert.equal(row[1], stars(f.star));
      assert.equal(row[2], f.star === 1 ? String(f.cost) : `↑${f.cost}`);
      assert.equal(row[3], `${f.might} / ${f.guard}`);
      const masterRules = [f.keywords.length ? `**${f.keywords.join(', ')}**` : '', f.text && f.ability ? `*${f.ability}*` : '', f.text, f.star === 3 ? '♛2' : ''].filter(Boolean).join(' · ') || '—';
      assert.equal(row[4], masterRules, `${row[0]}: card data/master list drift`);
      const keywordLines = f.keywords.map(k => {
        assert(reminders.has(k), `Missing exact reminder: ${k}`);
        return `${k} *${reminders.get(k)}*`;
      });
      const abilityLines = f.text && f.ability ? [`**${f.ability}.**`] : [];
      const textLines = [...keywordLines, ...abilityLines, ...rulesLines(f.text)];
      const traits = [...line.origins, ...line.classes].map(cap);
      const flavour = row[5];
      assert(flavour.startsWith('"') && flavour.endsWith('"'), `${row[0]}: missing flavour`);
      prompt.push(
        `Card number: ${row[0]} (${numbers[i]})`,
        f.star === 1 ? `Cost: ${f.cost} (GREEN gem)` : `Ascend cost: up-arrow ${f.cost} (GOLD gem showing an arrow pointing up and the number ${f.cost})`,
        `Name: ${line.name}`, `Title: ${line.title}`, `Stars: ${stars(f.star)}`,
        f.star === 1 ? 'No Ascension band' : `Ascension band: ASCENSION • from ${line.name} ${stars(f.star - 1)}`,
        `Origin | Class | Tier: ${line.origins.map(cap).join(' · ')} | ${line.classes.map(cap).join(' · ')} | ${tier.toUpperCase()}`,
        `Trait icons: ${traits.map(t => `${t}: ${icons.get(t) ?? 'use its icon from the official sheet'}`).join('; ')}`,
        `Keywords: ${keywordLines.join(' · ') || 'none (text box starts with the ability name)'}`,
        ...(!f.keywords.length && !abilityLines.length ? ['No ability name is listed; start with the first rules line below. Do not invent one.'] : []),
        'Text box, line by line:', ...textLines.map((t, n) => `${n + 1}. ${t}`),
        `Flavour: “${flavour.slice(1, -1)}”`,
        f.star === 3 ? `Crown 2: crown icon + 2 at the right end of the first text-box line (${keywordLines.length ? 'keyword' : abilityLines.length ? 'ability' : 'rules'} line).` : 'Crown 2: none',
        `Might | Guard: ${f.might} | ${f.guard}`,
        `Footer: ${numbers[i]}/${set === 1 ? 248 : 236} · ${rarityLetter} · Northern Summit Studios · Art: Jerian Latawiec`,
        `Art brief: ${row[6]}`, '',
      );
      if (f.star === 2 && f.cost !== 0) risks.push(`${numbers[i]} ★★: up-arrow ${f.cost}, not up-arrow 0.`);
      if (!f.keywords.length) risks.push(`${numbers[i]}: no keyword; do not add a chip or reminder.`);
      if (f.star === 3 && textLines.length >= 4) risks.push(`${numbers[i]} ★★★ has ${textLines.length} text lines before flavour; retain all lines and crown 2 placement.`);
      if (traits.some(t => !icons.has(t))) risks.push(`${numbers[i]}: unlisted traits use the official sheet; never invent icons.`);
    }
    const scorch = [...group.matchAll(/Scorch (\d+)/g)].map(m => m[1]);
    if (new Set(scorch).size > 1) risks.push(`Mixed Scorch numbers: ${rows.map(r => `${r[0]}: ${[...r[4].matchAll(/Scorch \d+/g)].map(m => m[0]).join(', ') || 'none'}`).join('; ')}.`);
    prompt.push('Check when it comes back:', ...[...new Set(risks)].map(r => `- ${r}`));
    writeFileSync(join(outputDir, `${filename}.txt`), prompt.join('\n') + '\n');
    const range = `${numbers[0]}–${numbers[2]}`;
    const status = set === 1 && Number(numbers[0]) <= 7 ? 'Approved' : set === 1 && numbers[0] === '010' ? 'Redo: frame drift (chevron band, empty band on ★, wrong crest)' : oldStatuses.get(`${set}:${range}`) ?? 'Not started';
    tracker.push(`| ${set} | ${line.name} | ${range} | set${set}/${filename}.jpg | ${status} |`);
    total++;
  }
}
writeFileSync(join(root, 'card-prompts/CARD_ART_TRACKER.md'), tracker.join('\n') + '\n');
console.log(`Generated ${total} champion prompts in master-list order and CARD_ART_TRACKER.md.`);
