import { mkdirSync, writeFileSync } from 'node:fs';
import { catalog, champions, decks, items, traits } from '../src/content/prototype';
import { prototypePrinting } from '../src/content/editions';

const escape = (value: string) => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
const sections = Object.entries(decks).map(([deckId, deck]) => {
  const cards = deck.ids.flatMap(id => [id, id, id]).map((id, index) => {
    const c = catalog[id], print = prototypePrinting(c.id, String(champions.findIndex(c => c.id === id) + 1).padStart(3, '0'));
    return `<article class="card"><header><b>${c.cost} COMMAND</b><span>TIER ${c.tier}</span></header><div class="art">${c.glyph}</div><h2>${escape(c.name)}</h2><p class="identity">${c.origin} / ${c.class}</p><p>${escape(c.text)}</p><div class="stats"><b>${c.might} MIGHT</b><b>${c.guard} BASE GUARD</b></div><p class="ascent">★★ +2 Might, +3 Guard<br>★★★ +4 Might, +6 Guard<br>Ascend: consume matching copy, pay 1 Command, fully mend.</p><footer>${print.gameplayCardId}<br>${deckId} / ${index + 1} / ${print.collectorNumber} · ${print.treatment}<br>NONCANONICAL PLAYTEST · rules 0.1</footer></article>`;
  });
  const pages = Array.from({ length: Math.ceil(cards.length / 9) }, (_, i) => `<section class="sheet">${cards.slice(i * 9, i * 9 + 9).join('')}</section>`);
  return `<section class="intro"><h1>${deck.name}</h1><p>${deck.description}</p><p>30 champion cards. Three copies each. These are test identities, not canonical Crownfall champions.</p><p>Cut at the borders. Print at 100% scale on A4 or US Letter (2.5 × 3.5 inch cards). Use card sleeves and backing cards. The Guard printed below is BASE Guard; Bulwark adds 1 per star.</p><h2>Decklist</h2>${deck.ids.map(id => `<p>3 × ${catalog[id].name} <small>${id}</small></p>`).join('')}<p>Full authoritative prototype rules: docs/RULES.md in the repository. No software required for tabletop play.</p></section>${pages.join('')}`;
}).join('');
const recipeCards = items.flatMap(item => Array.from({ length: 18 }, () => `<article class="card item"><header>FIXED FORGE RECIPE</header><div class="art">${item.id === 'shp-item-blade' ? '⚔' : '⬟'}</div><h2>${item.name}</h2><p>${item.text}</p><p>Spend 2 component counters + 1 Command.<br>Equip one champion. One item per champion.</p><p>Return to the shared supply when its champion falls. Items cannot be moved or replaced.</p><footer>${item.id}<br>NONCANONICAL PLAYTEST</footer></article>`));
const recipePages = Array.from({ length: 4 }, (_, i) => `<section class="sheet">${recipeCards.slice(i * 9, i * 9 + 9).join('')}</section>`).join('');
const supplies = `<section class="intro"><h1>Tabletop reference & supplies</h1><p>Two 30-card decks, three named fronts (Wild / Throne / Forge), one Crown marker and a 13-position track, two Sovereign markers, Command / component / wound / growth counters, round counter, claim marker, first-player marker. Stack consumed copies beneath champions to indicate stars.</p><h2>Round sequence</h2><p>Alternate one action: deploy (printed cost), move (1), ascend (1 + copy), forge/equip (1 + 2 components), or pass. Both pass consecutively: lock traits and Might → simultaneously deal Might front-to-back → remove fallen stacks → compare surviving locked Might → award front benefits → subtract influence and move Crown → check claim/victory → refresh Command and draw 2. Initiative alternates each round.</p><h2>Crown track</h2><div class="track">YOU ◇ — ◇ — ◇ — ◇ — ◇ — ◇ — ◆ — ◇ — ◇ — ◇ — ◇ — ◇ — ◇ RIVAL</div><p>Wild / Forge = 1 influence; Throne = 2. Reach your endpoint, then win net influence in a later resolution while at the endpoint. Ties delay. Reversal cancels. After round 18, nearer Crown wins; centre draws.</p><h2>Trait reference</h2>${traits.map(t => `<p><b>${t.name}</b>: ${t.scope}. ${t.text}</p>`).join('')}<p>Duplicate identities do not count twice. Lock every trait at battle start; no midbattle recalculation. Damage persists; Wild mends 1 and grows surviving winners by 1 (maximum +2).</p></section>${recipePages}`;
const html = `<!doctype html><html lang="en"><head><meta charset="UTF-8"><title>Sovereign’s Hand — print & play</title><style>@page{size:auto;margin:.2in}*{box-sizing:border-box}body{font-family:Arial,sans-serif;margin:0;color:#222;background:#eee}.toolbar{padding:25px;background:#152522;color:#eee}button{padding:10px}.sheet{display:grid;grid-template-columns:repeat(3,2.5in);grid-auto-rows:3.5in;gap:0;break-after:page;width:7.5in;margin:auto;background:white}.card{border:1px dashed #888;width:2.5in;height:3.5in;padding:.13in;position:relative;font-size:9pt;overflow:hidden}.card header{display:flex;justify-content:space-between;font-size:8pt;border-bottom:1px solid #888;padding-bottom:.06in}.art{height:.72in;display:grid;place-items:center;font-size:34pt;color:#555}.card h2{font-size:14pt;margin:.04in 0}.identity{font-size:8pt}.card p{line-height:1.45}.stats{display:flex;justify-content:space-between;font-size:9pt;border-top:1px solid #aaa;padding-top:8px}.ascent{font-size:8pt}.card footer{position:absolute;bottom:.1in;left:.13in;right:.13in;font-size:6pt;line-height:1.4;color:#555}.intro{padding:.3in;max-width:7.5in;margin:auto;background:white;break-after:page;min-height:10in}.intro h1{font:28pt Georgia,serif}.intro p{font-size:11pt;line-height:1.6}.intro small{color:#666}.track{padding:15px 0;font-size:12pt;white-space:nowrap}.item{margin:0}.item .art{height:.55in}.item p{font-size:9pt;line-height:1.4;margin:.1in 0}@media print{body{background:white}.toolbar{display:none}.intro{padding:.15in;min-height:0}.sheet{margin:0}}</style></head><body><div class="toolbar"><h1>Crownfall: Sovereign’s Hand — tabletop playtest kit</h1><p>Noncanonical prototype. Two complete starter decks, item supplies, rules reference. Full rules accompany this file in docs/RULES.md.</p><button onclick="window.print()">Print at 100% scale</button></div>${sections}${supplies}</body></html>`;
mkdirSync('public', { recursive: true }); writeFileSync('public/print-and-play.html', html);
console.log('Generated public/print-and-play.html: 60 champion cards, 36 reusable items, two decklists and tabletop reference.');
